# Generated by Django 5.0.6 on 2024-06-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_location_location_id_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('representation_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='representation_id')),
                ('schedule', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='catalogue.location')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='catalogue.spectacle')),
            ],
            options={
                'db_table': 'representations',
            },
        ),
    ]
