# Generated by Django 5.0.6 on 2024-06-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('langue', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ArtisteType',
            fields=[
                ('artiste_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.type')),
            ],
            options={
                'db_table': 'artiste_type',
            },
        ),
        migrations.CreateModel(
            name='ArtisteTypeSpectacle',
            fields=[
                ('artiste_type_spectacle_id', models.AutoField(primary_key=True, serialize=False)),
                ('artiste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artistetype')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.spectacle')),
            ],
            options={
                'db_table': 'artiste_type_spectacle',
            },
        ),
        migrations.CreateModel(
            name='RepresentationReservation',
            fields=[
                ('representation_reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.prices')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.reservations')),
            ],
            options={
                'db_table': 'representation_reservation',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('role_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.users')),
            ],
            options={
                'db_table': 'role_user',
            },
        ),
        migrations.AddField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.users'),
        ),
    ]
